### ISSUE TITLE
forEach时EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by liTao-leven** [nerdycat/NerdyUI#10]
![image](https://user-images.githubusercontent.com/17468545/40046414-812d1bb2-585f-11e8-83d2-367e230b9df6.png)
![image](https://user-images.githubusercontent.com/17468545/40046453-948c3dfa-585f-11e8-86e1-1da5d205437d.png)
![image](https://user-images.githubusercontent.com/17468545/40046843-80cd7990-5860-11e8-9f14-909cd83a4d07.png)

ps:
> * 测试环境:iPhoneX模拟器
> * 真机环境下没问题
> * 改为for in 没问题

**Comment by FE-Sakamoto** [comment]
forEach的return应该是void他这里写成了id 应该是bug.
你可以临时在forEach的block内加个 return nil
