### ISSUE TITLE
ios 13.4 crash

### ISSUE THREAD

**Issue by miaoruiyuan** [nerdycat/NerdyUI#15]
Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)
能修复下么

**Comment by wt067531** [comment]
<img width="965" alt="nerdyui" src="https://user-images.githubusercontent.com/1826467/77873447-989a9480-727c-11ea-80c8-5f4ee93a0240.png">
去掉工程中   Main Thread Checker 的勾选

**Comment by miaoruiyuan** [comment]
@wt067531 嗯 原因是label 的color属性 不知道和工程里哪个也带color的冲突了  改名之后好了

**Comment by wt067531** [comment]
是13.4UILabel自带的隐藏属性，可以在调试时用runtime打印出来.改名字对于工程来说代价有点大
