### ISSUE TITLE
Property 'hint' not found

### ISSUE THREAD

**Issue by 260146874wl** [nerdycat/NerdyUI#2]
Property 'hint' not found on object of type 'UITextView *'

**Comment by nerdycat** [comment]
@260146874wl 你是运行 demo 还是自己的代码时出现的问题呢？ 如果是自己的代码可以发出来看一下吗？

**Comment by 260146874wl** [comment]
@nerdycat 自己新建的工程用的pod 'NerdyUI','0.0.2'，就是复制粘贴你这里的代码呀，还有这句：Alert.title(@"Title").message(@"Message").action(@"OK",^{
    }), cancel(@"Cancel").show();也报错了，错误提示:Member reference base type 'int' is not a structure or union.....其他的都好使,,,我看你的.h文件了，我这版本里面没有NER_TF_PROP(Object)     hint;

**Comment by 260146874wl** [comment]
@nerdycat 我的问题，没用最新版，我以为0.0.2是最新的呢，不用cocospod直接拽项目中也可以吗，不依赖其他库吗？

**Comment by 260146874wl** [comment]
@nerdycat cocospod只能搜索到0.0.2版本，你给更新下0.0.4吧

**Comment by nerdycat** [comment]
@260146874wl https://cocoapods.org/pods/NerdyUI
最新是0.0.5，如果搜不到的话麻烦更新一下cocoapods或cocoapods本地缓存

**Comment by nerdycat** [comment]
pod已更新，请留意。
如果不想使用pod安装，直接拷贝文件也可以的。
