### ISSUE TITLE
Demo run crash

### ISSUE THREAD

**Issue by cpj123456** [nerdycat/NerdyUI#3]
![image](https://cloud.githubusercontent.com/assets/16045764/23113909/693e2eec-f776-11e6-98fe-5b187d30e99c.png)

**Comment by cpj123456** [comment]
Demo中用pod后，NerdyUI版本0.0.5，但会crash

**Comment by nerdycat** [comment]
@cpj123456 Demo直接运行即可，不需要再用pod安装。

**Comment by cpj123456** [comment]
直接运行也是一样的问题
![image](https://cloud.githubusercontent.com/assets/16045764/23116914/0f1ef1f0-f788-11e6-8358-024ea7b0028e.png)

配置
![image](https://cloud.githubusercontent.com/assets/16045764/23116958/5110bec2-f788-11e6-9445-488a0d349dfa.png)

**Comment by nerdycat** [comment]
@cpj123456 麻烦加一下qq: 28578093

**Comment by nerdycat** [comment]
已确定在64-bit设备上运行会crash，请大家暂时不要使用，修复后会在此通知。

**Comment by cpj123456** [comment]
收到

**Comment by nerdycat** [comment]
崩溃问题已修复，请下载最新代码或 pod update
