### ISSUE TITLE
引入第三库后编译报错

### ISSUE THREAD

**Issue by ACoderNHC** [nerdycat/NerdyUI#5]
你好，我引入了第三方库，该库有C++混编的代码，编译报错，如下图，请问怎么解决？
![error](https://cloud.githubusercontent.com/assets/13420240/23354245/2e0b83a2-fd0b-11e6-9945-7668b8bc1c9d.jpeg)

**Comment by nerdycat** [comment]
已经修复C++混编报错问题。
Fixed Error when working with Objective-C++。
