### ISSUE TITLE
复合型cell

### ISSUE THREAD

**Issue by shaozhe-chen** [nerdycat/NerdyUI#6]
关于复合型cell，有什么好建议么？比如有些控件需要隐藏，有些控件需要显示。比如3个控件HorStack(view1,view2,view3),我需要隐藏view2，怎么做到view3自动移到view2的位置。希望大神给点建议啊。

**Comment by shaozhe-chen** [comment]
看了源码才发现，原来只要设置hidden就可以了。

**Comment by nerdycat** [comment]
@shaozhe-chen 是的，就跟 UIStackView 一样。

**Comment by shaozhe-chen** [comment]
好方便。
